# Generated by Django 4.2.30 on 2026-06-27 12:54

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='clinic_post_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v']), core.validators.validate_video_size]),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['clinic', '-created_at'], name='posts_post_clinic__1f1fd5_idx'),
        ),
    ]
