# Generated by Django 5.2.7 on 2025-10-26 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Brief tagline for your clinic', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of your clinic services and approach')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('specialization', models.CharField(choices=[('Physical Therapy', 'Physical Therapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Sports Medicine', 'Sports Medicine'), ('Orthopedic Rehabilitation', 'Orthopedic Rehabilitation'), ('Neurological Rehabilitation', 'Neurological Rehabilitation'), ('Cardiac Rehabilitation', 'Cardiac Rehabilitation'), ('Pediatric Rehabilitation', 'Pediatric Rehabilitation'), ('Geriatric Rehabilitation', 'Geriatric Rehabilitation'), ('Pain Management', 'Pain Management'), ('Post-Surgical Rehabilitation', 'Post-Surgical Rehabilitation')], max_length=50)),
                ('other_specializations', models.CharField(blank=True, help_text='Other specializations (comma separated)', max_length=200)),
                ('license_number', models.CharField(max_length=50)),
                ('established_date', models.DateField()),
                ('facilities', models.CharField(blank=True, help_text='Available facilities (comma separated)', max_length=500)),
                ('number_of_therapists', models.PositiveIntegerField(default=1)),
                ('languages_spoken', models.CharField(default='English', help_text='Languages spoken (comma separated)', max_length=200)),
                ('hours_of_operation', models.TextField(default='Mon-Fri: 9:00 AM - 6:00 PM\nSat: 9:00 AM - 1:00 PM')),
                ('profile_picture', models.ImageField(blank=True, help_text='Main profile picture of your clinic', null=True, upload_to='clinic_profile_pics/')),
                ('cover_photo', models.ImageField(blank=True, help_text='Cover photo for your clinic page', null=True, upload_to='clinic_cover_photos/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes for the clinic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinic_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='clinics.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_range', models.CharField(blank=True, help_text='e.g., $100-$150 per session', max_length=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'unique_together': {('clinic', 'patient')},
            },
        ),
    ]
