# Generated by Django 5.2.7 on 2025-11-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientAssignment',
        ),
    ]
