# Generated by Django 5.2.7 on 2026-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_delete_patientassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepts_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using a catheter'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_heart_problems',
            field=models.BooleanField(default=True, help_text='Accept patients with heart problems'),
        ),
    ]
