# Generated by Django 5.2.7 on 2026-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_accepts_catheter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepts_bedsores',
            field=models.BooleanField(default=True, help_text='Accept patients with bedsores'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_bowel_incontinence',
            field=models.BooleanField(default=True, help_text='Accept patients with bowel incontinence'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_breathing_issues',
            field=models.BooleanField(default=True, help_text='Accept patients with breathing issues'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_crutch',
            field=models.BooleanField(default=True, help_text='Accept patients who use crutches'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_depression',
            field=models.BooleanField(default=True, help_text='Accept patients with depression'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_diabetes',
            field=models.BooleanField(default=True, help_text='Accept patients with diabetes'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_diapers',
            field=models.BooleanField(default=True, help_text='Accept patients using diapers'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_electric_wheelchair',
            field=models.BooleanField(default=True, help_text='Accept patients who use an electric wheelchair'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_feeding_tube',
            field=models.BooleanField(default=True, help_text='Accept patients using a feeding tube'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_high_blood_pressure',
            field=models.BooleanField(default=True, help_text='Accept patients with high blood pressure'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_infectious_diseases',
            field=models.BooleanField(default=True, help_text='Accept patients with infectious diseases'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_insulin',
            field=models.BooleanField(default=True, help_text='Accept patients using insulin'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_medical_condom',
            field=models.BooleanField(default=True, help_text='Accept patients using a medical condom'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_stool_tube',
            field=models.BooleanField(default=True, help_text='Accept patients using a stool tube'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_urine_incontinence',
            field=models.BooleanField(default=True, help_text='Accept patients with urine incontinence'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_urine_tube',
            field=models.BooleanField(default=True, help_text='Accept patients using a urine tube'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_vein_thrombosis',
            field=models.BooleanField(default=True, help_text='Accept patients with vein thrombosis'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_walker',
            field=models.BooleanField(default=True, help_text='Accept patients who use a walker'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_wheelchair',
            field=models.BooleanField(default=True, help_text='Accept patients who use a wheelchair'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='accepts_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using a catheter (permanent or intermittent)'),
        ),
    ]
