# Generated by Django 5.2.7 on 2026-01-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='clinic',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
