# Generated by Django 5.2.7 on 2026-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_post_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
