# Generated by Django 5.2.7 on 2026-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps link to your clinic location'),
        ),
    ]
