# Generated by Django 5.2.7 on 2026-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL (from Share → Embed a map → Copy src URL)'),
        ),
    ]
