# Generated by Django 4.2.28 on 2026-03-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_alter_clinic_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='license_number',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
    ]
