# Generated by Django 4.2.28 on 2026-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_remove_clinic_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicservice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clinic_services/'),
        ),
    ]
