# Generated by Django 4.2.28 on 2026-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_medical_tourism_request_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='other_specializations',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='specialization',
            field=models.TextField(help_text='Primary specialization(s) (comma separated)'),
        ),
    ]
