# Generated by Django 4.2.28 on 2026-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_remove_clinic_other_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='requested_clinic_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
