# Generated by Django 4.2.28 on 2026-03-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0017_alter_appointment_requested_clinic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('single_room', 'Single room'), ('double_room', 'Double room'), ('double_suite', 'Double suite'), ('quad_suite', 'Quad suite'), ('no_accommodation', 'No accommodation')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='companions_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='facility_response',
            field=models.CharField(choices=[('pending', 'Pending Facility Response'), ('accept_requested_dates', 'Accept the booking on the requested dates'), ('accept_propose_different_dates', 'Accept but propose different dates'), ('reject_booking', 'Reject the booking')], default='pending', max_length=40),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_date_action',
            field=models.CharField(choices=[('pending', 'Pending Patient Action'), ('accept_new_dates', 'Patient accepted new dates'), ('choose_different_dates', 'Patient requested different dates')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='proposed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='proposed_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('clinic_date_change_proposed', 'Clinic Proposed Different Dates'), ('patient_date_change_requested', 'Patient Requested Different Dates'), ('payed', 'Payed'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(blank=True, choices=[('Convalescence', 'Convalescence'), ('Weight loss', 'Weight loss'), ('Musculoskeletal treatment', 'Musculoskeletal treatment'), ('Neurological treatment', 'Neurological treatment')], default='', max_length=50),
        ),
    ]
