# Generated by Django 4.2.28 on 2026-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_appointment_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic_proposal_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_response_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_date_action',
            field=models.CharField(choices=[('pending', 'Pending Patient Action'), ('accept_new_dates', 'Patient accepted new dates'), ('choose_different_dates', 'Patient requested different dates'), ('decline_proposed_change', 'Patient declined proposed change')], default='pending', max_length=30),
        ),
    ]
