# Generated by Django 4.2.28 on 2026-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_appointment_clinic_proposal_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('payment_pending', 'Waiting for Payment'), ('clinic_date_change_proposed', 'Clinic Proposed Different Dates'), ('patient_date_change_requested', 'Patient Requested Different Dates'), ('payed', 'Payed'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
