# Generated by Django 4.2.28 on 2026-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0022_appointment_medical_rejection_reason_and_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='accommodation_review_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='facility_response',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medical_review_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_date_action',
        ),
        migrations.AddField(
            model_name='appointment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic_proposal_note',
            field=models.TextField(blank=True, default='', help_text="Clinic's proposed changes to accommodation/dates"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_response_note',
            field=models.TextField(blank=True, default='', help_text="Patient's response to clinic's proposed changes"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted_record_accepted_accommodation', 'Accepted - Record & Accommodation Accepted'), ('accepted_record_accommodation_change_requested', 'Accepted - Accommodation Change Requested'), ('rejected_medical_record', 'Rejected - Medical Record Declined'), ('cancelled', 'Cancelled'), ('waiting_for_payment', 'Waiting for Payment'), ('paid', 'Paid'), ('upcoming', 'Upcoming')], default='pending', max_length=50),
        ),
    ]
