# Generated by Django 4.2.28 on 2026-04-03 15:28

from django.db import migrations


def migrate_statuses_forward(apps, schema_editor):
    """Migrate old appointment statuses to new 8-status system."""
    Appointment = apps.get_model('clinics', 'Appointment')
    
    # Mapping of old statuses to new statuses
    status_mapping = {
        'payment_pending': 'waiting_for_payment',
        'payed': 'paid',
        'accepted': 'accepted_record_accepted_accommodation',
        'patient_date_change_requested': 'accepted_record_accommodation_change_requested',
        'clinic_date_change_proposed': 'accepted_record_accommodation_change_requested',
        'awaiting_accommodation': 'accepted_record_accepted_accommodation',
        'completed': 'upcoming',  # Terminal state mapping
        'rejected': 'rejected_medical_record',
    }
    
    # Update appointments with old statuses
    for old_status, new_status in status_mapping.items():
        Appointment.objects.filter(status=old_status).update(status=new_status)


def migrate_statuses_backward(apps, schema_editor):
    """Reverse migration - restore old statuses (for rollback)."""
    Appointment = apps.get_model('clinics', 'Appointment')
    
    # Reverse mapping
    reverse_mapping = {
        'waiting_for_payment': 'payment_pending',
        'paid': 'payed',
        'accepted_record_accepted_accommodation': 'accepted',
        'rejected_medical_record': 'rejected',
    }
    
    for new_status, old_status in reverse_mapping.items():
        Appointment.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_remove_appointment_accommodation_review_status_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses_forward, migrate_statuses_backward),
    ]
