# Generated by Django 4.2.28 on 2026-04-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0024_migrate_appointment_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_record_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
