# Generated by Django 4.2.28 on 2026-04-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0021_appointment_medical_rejection_reason_and_status'),
        ('clinics', '0026_appointment_payment_amount'),
    ]

    operations = [
    ]
