# Generated by Django 4.2.30 on 2026-06-27 12:54

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0027_merge_20260412_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted_record_accepted_accommodation', 'Accepted - Record & Accommodation Accepted'), ('accepted_record_accommodation_change_requested', 'Accepted - Accommodation Change Requested'), ('rejected_medical_record', 'Rejected - Medical Record Declined'), ('cancelled', 'Cancelled'), ('waiting_for_payment', 'Waiting for Payment'), ('paid', 'Paid'), ('upcoming', 'Upcoming')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='clinic_post_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v']), core.validators.validate_video_size]),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'status'], name='clinics_app_clinic__6cf122_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='clinics_app_patient_189624_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['clinic', '-created_at'], name='clinics_pos_clinic__4d7012_idx'),
        ),
    ]
