# Generated by Django 4.2.30 on 2026-09-13 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0028_alter_appointment_status_alter_clinic_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_intermittent_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using an intermittent catheter'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_permanent_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using a permanent catheter'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the clinic was established (e.g. 2015)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        # NOTE (hand-edited): the old free-text `facilities` column is RENAMED
        # to `facilities_text` (not dropped + re-added) so existing data is kept.
        migrations.RenameField(
            model_name='clinic',
            old_name='facilities',
            new_name='facilities_text',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='accepts_catheter',
            field=models.BooleanField(default=True, help_text='LEGACY — synced from permanent/intermittent catheter flags. Do not edit directly.'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='accepts_medical_condom',
            field=models.BooleanField(default=True, help_text='Accept patients using a medical condom Catheter'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(blank=True, default='', help_text='LEGACY — synced from clinic_types. Do not edit directly.', max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='established_date',
            field=models.DateField(blank=True, help_text='LEGACY — synced from established_year. Do not edit directly.', null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='facilities_text',
            field=models.CharField(blank=True, default='', help_text='LEGACY — synced from facilities. Do not edit directly.', max_length=500),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='specialization',
            field=models.TextField(help_text='LEGACY — synced from specializations. Do not edit directly.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_types',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='clinics.clinictype'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='clinics.specialization'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='clinics.facility'),
        ),
    ]
