# Generated by Django 4.2.30 on 2026-09-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0028_alter_appointment_status_alter_clinic_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='accepts_electric_wheelchair',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='hours_of_operation',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='number_of_therapists',
        ),
    ]
