# Generated by Django 4.2.30 on 2026-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0029_restore_clinic_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepts_bedridden_patients',
            field=models.BooleanField(default=True, help_text='Accept bedridden patients'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_dependent_patients',
            field=models.BooleanField(default=True, help_text='Accept dependent patients'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_tracheostomy_tube',
            field=models.BooleanField(default=True, help_text='Accept patients using a tracheostomy tube'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='age_range',
            field=models.CharField(choices=[('adults_only', 'Adults only'), ('children_only', 'Children only'), ('both', 'Both adults and children')], default='both', help_text='Patient age group treated by the clinic', max_length=20),
        ),
    ]
