# Generated by Django 4.2.30 on 2026-09-13 16:45

import django.core.validators
from django.db import migrations, models


def migrate_catheter_and_year(apps, schema_editor):
    """Copy legacy values into the new columns BEFORE the old ones are dropped.

    - accepts_catheter=True meant 'accepts both kinds' -> set both new flags.
    - established_year comes from established_date.
    New columns default to True/empty, so rows are safe even if this is skipped.
    """
    Clinic = apps.get_model('clinics', 'Clinic')
    for clinic in Clinic.objects.all():
        if clinic.accepts_catheter:
            clinic.accepts_permanent_catheter = True
            clinic.accepts_intermittent_catheter = True
        else:
            clinic.accepts_permanent_catheter = False
            clinic.accepts_intermittent_catheter = False
        if clinic.established_date and not clinic.established_year:
            clinic.established_year = clinic.established_date.year
        clinic.save()


def migrate_backward(apps, schema_editor):
    Clinic = apps.get_model('clinics', 'Clinic')
    for clinic in Clinic.objects.all():
        clinic.accepts_catheter = bool(
            clinic.accepts_permanent_catheter or clinic.accepts_intermittent_catheter
        )
        clinic.save(update_fields=['accepts_catheter'])


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0029_remove_clinic_accepts_electric_wheelchair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepts_intermittent_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using an intermittent catheter'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_permanent_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using a permanent catheter'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the clinic was established (e.g. 2015)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.RunPython(migrate_catheter_and_year, migrate_backward),
        migrations.RemoveField(
            model_name='clinic',
            name='accepts_catheter',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='established_date',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='accepts_medical_condom',
            field=models.BooleanField(default=True, help_text='Accept patients using a medical condom Catheter'),
        ),
    ]
