# Generated by Django 4.2.30 on 2026-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0030_remove_clinic_accepts_catheter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepts_bedridden_patients',
            field=models.BooleanField(default=True, help_text='Accept Bedridden patients'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_dependent_patients',
            field=models.BooleanField(default=True, help_text='Accept Dependent patients'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_tracheostomy_tube',
            field=models.BooleanField(default=True, help_text='Accept patients using tracheostomy tube'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='age_range',
            field=models.CharField(choices=[('adults_only', 'Adults only'), ('children_only', 'Children only'), ('both', 'Both adults and children')], default='both', help_text='Patient age group the clinic treats', max_length=20),
        ),
    ]
