# Generated by Django 4.2.30 on 2026-10-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0031_remove_clinic_accepts_electric_wheelchair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='accepts_catheter',
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_intermittent_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using an intermittent catheter'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_permanent_catheter',
            field=models.BooleanField(default=True, help_text='Accept patients using a permanent catheter'),
        ),
    ]
