# Generated by Django 4.2.30 on 2026-10-09 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0032_remove_clinic_clinic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='user',
            field=models.ForeignKey(help_text='Account that owns/manages this clinic. One account may own multiple clinics.', on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to=settings.AUTH_USER_MODEL),
        ),
    ]
