from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.clinic_signup_view, name='clinic_signup'),
    path('dashboard/', views.clinic_dashboard_view, name='clinic_dashboard'),
    path('ping/', views.clinic_ping, name='clinic_ping'),
    path('settings/', views.clinic_settings_view, name='clinic_settings'),
    path('detail/<int:clinic_id>/', views.clinic_detail_view, name='clinic_detail'),
    path('detail-clinic/<int:clinic_id>/', views.clinic_detail_clinic_view, name='clinic_datils_clinic'),
    path('manage-gallery/', views.manage_gallery_view, name='manage_gallery'),
    path('delete-gallery-image/<int:image_id>/', views.delete_gallery_image_view, name='delete_gallery_image'),
    path('service/<int:service_id>/delete/', views.delete_clinic_service_view, name='delete_clinic_service'),
    path('assign-patient/<int:patient_id>/', views.assign_patient_view, name='assign_patient'),
    path('appointments/', views.clinic_appointments_view, name='clinic_appointments_legacy'),
    path('clinic-appointments/', views.clinic_appointments_view, name='clinic_appointments'),
    path('appointment/<int:appointment_id>/update-status/', views.update_appointment_status_view, name='update_appointment_status'),
    path('appointment/<int:appointment_id>/medical-accept/', views.accept_medical_record_view, name='accept_medical_record'),
    path('appointment/<int:appointment_id>/medical-reject/', views.reject_medical_record_view, name='reject_medical_record'),
    path('appointment/<int:appointment_id>/facility-accept-requested-dates/', views.facility_accept_requested_dates_view, name='facility_accept_requested_dates'),
    path('appointment/<int:appointment_id>/set-payment-amount/', views.set_payment_amount_view, name='set_payment_amount'),
    path('appointment/<int:appointment_id>/mark-upcoming/', views.mark_appointment_upcoming_view, name='mark_appointment_upcoming'),
    path('appointment/<int:appointment_id>/google-calendar/start/', views.clinic_google_calendar_start_view, name='clinic_google_calendar_start'),
    path('google-calendar/callback/', views.clinic_google_calendar_callback_view, name='clinic_google_calendar_callback'),
    path('appointment/<int:appointment_id>/facility-propose-dates/', views.facility_accept_propose_dates_view, name='facility_propose_dates'),
    path('appointment/<int:appointment_id>/facility-reject-booking/', views.facility_reject_booking_view, name='facility_reject_booking'),
    path('appointment/<int:appointment_id>/accommodation-with/', views.accept_with_accommodation_view, name='accept_with_accommodation'),
    path('appointment/<int:appointment_id>/accommodation-without/', views.accept_without_accommodation_view, name='accept_without_accommodation'),
    path('patient/<int:patient_id>/', views.patient_detail_view, name='patient_detail'),
    path('search-patients/', views.search_patients_view, name='search_patients'),
    path('search-patient-clinic/', views.search_patient_clinic_page, name='search_patient_clinic'),
    path('my-posts/', views.clinic_my_posts_view, name='clinic_my_posts'),
    path('my-posts/<int:post_id>/edit/', views.edit_post_view, name='edit_post'),
    path('my-posts/<int:post_id>/delete/', views.delete_post_view, name='delete_post'),
    
]