# Generated by Django 4.2.30 on 2026-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_blocking_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'is_read'], name='chat_messag_chat_ro_450d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chat_messag_timesta_6494d7_idx'),
        ),
    ]
