# Generated by Django 4.2.28 on 2026-02-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('block_count', models.PositiveIntegerField(default=0, help_text='Number of times this IP has been blocked')),
                ('first_blocked', models.DateTimeField(auto_now_add=True)),
                ('last_blocked', models.DateTimeField(auto_now=True)),
                ('is_permanently_blocked', models.BooleanField(default=False, help_text='IP is permanently blocked after 3+ blocks')),
                ('reason', models.TextField(blank=True, help_text='Reason for permanent block')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocked IP Record',
                'verbose_name_plural': 'Blocked IP Records',
                'ordering': ['-last_blocked'],
            },
        ),
    ]
