# Generated by Django 5.2.7 on 2026-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='has_catheter',
            field=models.BooleanField(default=False, help_text='Is the patient using a catheter?'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='has_heart_problems',
            field=models.BooleanField(default=False, help_text='Does the patient have heart problems?'),
        ),
    ]
