# Generated by Django 5.2.7 on 2026-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
