# Generated by Django 5.2.7 on 2026-02-01 10:23

import django.core.validators
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_reports',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']), patients.models.validate_file_size_3mb]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient_movement_video',
            field=models.FileField(blank=True, help_text="Upload a video showing patient's movement ability", null=True, upload_to='movement_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), patients.models.validate_file_size_50mb]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='patient_profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']), patients.models.validate_file_size_3mb]),
        ),
    ]
