# Generated by Django 5.2.7 on 2026-02-01 10:47

import django.core.validators
import patients.models
import patients.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_medicalrecord_medical_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_reports',
            field=models.FileField(blank=True, null=True, storage=patients.storage.EncryptedFileSystemStorage(), upload_to='medical_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']), patients.models.validate_file_size_3mb]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient_movement_video',
            field=models.FileField(blank=True, help_text="Upload a video showing patient's movement ability", null=True, storage=patients.storage.EncryptedFileSystemStorage(), upload_to='movement_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), patients.models.validate_file_size_50mb]),
        ),
    ]
