# Generated by Django 4.2.28 on 2026-03-29 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import patients.models
import patients.storage


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_medicalrecord_medical_reports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=patients.storage.EncryptedFileSystemStorage(), upload_to='movement_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), patients.models.validate_file_size_50mb])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='patients.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=patients.storage.EncryptedFileSystemStorage(), upload_to='medical_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), patients.models.validate_file_size_3mb])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.medicalrecord')),
            ],
        ),
    ]
