# Generated by Django 4.2.30 on 2026-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_medicalrecordvideo_medicalrecordreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
