# Generated by Django 4.2.30 on 2026-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='social_avatar_url',
            field=models.URLField(blank=True, default='', help_text='Avatar URL from a social login (e.g. Google).', max_length=500),
        ),
    ]
