# Generated by Django 4.2.30 on 2026-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_social_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='onboarding_done',
            field=models.BooleanField(default=False, help_text='First-run dashboard tour (King George onboarding) completed.'),
        ),
    ]
