# Generated by Django 4.2.30 on 2026-08-02 12:10

import django.core.validators
from django.db import migrations, models
import patients.models
import patients.storage


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_existing_patients_skip_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_reports',
            field=models.FileField(blank=True, null=True, storage=patients.storage.PrivateMedicalObjectStorage(), upload_to='medical_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']), patients.models.validate_file_size_3mb]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient_movement_video',
            field=models.FileField(blank=True, help_text="Upload a video showing patient's movement ability", null=True, storage=patients.storage.PrivateMedicalObjectStorage(), upload_to='movement_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), patients.models.validate_file_size_50mb]),
        ),
        migrations.AlterField(
            model_name='medicalrecordreport',
            name='file',
            field=models.FileField(storage=patients.storage.PrivateMedicalObjectStorage(), upload_to='medical_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), patients.models.validate_file_size_3mb]),
        ),
        migrations.AlterField(
            model_name='medicalrecordvideo',
            name='file',
            field=models.FileField(storage=patients.storage.PrivateMedicalObjectStorage(), upload_to='movement_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), patients.models.validate_file_size_50mb]),
        ),
    ]
