# Generated by Django 4.2.30 on 2026-09-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_medicalrecord_medical_reports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='uses_electric_wheelchair',
        ),
    ]
