# Generated by Django 4.2.30 on 2026-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_medicalrecord_medical_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='uses_tracheostomy_tube',
            field=models.BooleanField(default=False),
        ),
    ]
