# Generated by Django 4.2.30 on 2026-09-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_medicalrecord_uses_tracheostomy_tube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='uses_electric_wheelchair',
        ),
    ]
